language: python
sudo: false
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
install:
- pip install python-coveralls
- pip install -q -r requirements.txt
- pip install --editable .
before_script: flake8
script:
- coverage run --source=usernames/ --omit='*tests*' -m py.test tests/ -v --tb=native
- coverage report
after_script:
- coveralls
deploy:
  provider: pypi
  user: theskumar
  password:
    secure: DBGKZgPvE9wUsz0PrsB4ooGTqcOpTSsLbwora1JMX1DVB0t5GhGl66CYhouw3hSm3+ud9jZhxn2EAtVPMKQ4XRbfSAlPqg/FhPo+Gn7CpSHz/ZlFGmQ73rL+uKnJi72rP1s9h6xDCJfRt1eoZRNC6KL+7WW5W37KM7TjdVxxMF58FLEEJCZ4GfKf/Vg35ISLKrUtAEmf4nCoNN2UhfYozZ9Yb+2qNwM5yfPEOqHjjfrGbkTA5hvorTg5lZgbl/1xYGvmXb0ep6Aal4wlHi/rS1o+YR+Q/ctmqZ/FFz0Iq+Ky9OUGVkDFgDz29eiLqlZxOM3ciZbZSI708ltchk3dNeluFgzfHD9l6SrzX5rnUm8oZ8Bqmej5lqxbuRfyp2ZRjRcbQP5LfWdiyZ1V0NzySHnKYn9cj4fUqPZPu8nB4y/765dn39QGyJfoWcA+UIrb/4Itn1/cNJ7wXCz2NeuhJJnZHg2RWvnCiSiwOSVcsf+DyjYA2F/17fEKXrwBAt3HiQHwvVE5CNVwNCFP9HSmZjwZw0nBvQio9tPofS4rgTd//Ot4sWcAQG0MI0R3HnvM/xeGEsdSxoO2RCQx9jDxcvI2G0UmnBoO0SuGfozDKZ758s8URsUvOS3hiCrxHmm3rtWVpkb0gpgD2a6U6VeOKAEQHObA2AM73NWb+DF0heE=
  on:
    tags: true
    repo: theskumar/python-usernames
